name: Test Node Setup Script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-setup-script:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [16, 18, 20]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Run setup script
      shell: bash
      run: |
        sh check-node-version
        exit_code=$?
        if [ $exit_code -eq 0 ]; then
          echo "Script passed: Node version is sufficient"
        elif [ $exit_code -eq 1 ]; then
          if [ ${{ matrix.node-version }} -lt 18 ]; then
            echo "Script passed: Lower Node version detected, exit code 1 as expected"
          else
            echo "Script failed: Unexpected exit code 1 for Node version ${{ matrix.node-version }}"
            exit 1
          fi
        else
          echo "Script failed: Unexpected exit code $exit_code"
          exit 1
        fi
