name: Test Node Setup Script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-setup-script:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [16, 18, 20]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Run setup script
      shell: bash
      run: |
        # Capture output and exit code without failing on non-zero exit
        output=$(sh check-node-version 2>&1) || true
        echo "$output"
        
        if echo "$output" | grep -q "Success: Node.js.*is already installed and meets the minimum version requirement"; then
          echo "Script passed: Node version is sufficient"
          exit 0
        elif echo "$output" | grep -q "nvm is not installed"; then
          if [ ${{ matrix.node-version }} -lt 18 ]; then
            echo "Script passed: Lower Node version detected, nvm installation instructions provided"
            exit 0
          else
            echo "Script failed: Unexpected nvm message for Node version ${{ matrix.node-version }}"
            exit 1
          fi
        else
          echo "Script failed: Unexpected output"
          exit 1
        fi
